name: Periodic healthcheck

on:
  schedule:
    - cron: '0 10'

jobs:
  hello_world_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://intense-springs-16505.herokuapp.com/ping
          follow-redirect: no
          max-attempts: 3
          retry-delay: 5s
          retry-all: no