name: Periodic healthcheck

on:
  schedule:
    - cron: '0 12 * * *'

jobs:
  hello_world_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://intense-springs-16505.herokuapp.com/ping
          checkstring: "pong"
